name: test-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: diivanov/php:8.3-cli
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check composer version
        run: >
          composer --version
