name: test-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
      image: magento/magento-cloud-docker-php:8.3-cli-1.3.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check composer version
        run: |
          composer --version
          touch test
          ls -la
          pwd
